### ISSUE TITLE
[FR] BL touch examples now missing?  

### ISSUE THREAD

**Issue by dasflux** [JimBrown/MarlinTarantula#12]
Followed in to grab your firmware link on the tevo tarantula subreddit thats stickied

https://github.com/JimBrown/MarlinTarantula/tree/bugfix-1.1.x

And its missing.  But I could not find the BL touch examples.  Can you add those back?  They always worked perfectly for me.

**Comment by JimBrown** [comment]
That is an old link. I no longer have separate configs for different things. All combined in an EasyConfig section (including BLTouch stuff). Grab EasyConfig-Bugfix and read the comments at the top of configuration.h file.
