### ISSUE TITLE
Display freezing

### ISSUE THREAD

**Issue by rudemutant** [JimBrown/MarlinTarantula#13]
### Bug Report
- Description: --- display freezes early in print, but printer continues to print
- Expected behaviour: --- on TEVO Tarantula, expect to have control of the display.
- Actual behaviour: --- display freezes and knob is unresponsive. pushing knob will beep once, but only once.
- Steps to reproduce:
  - Print something, intermittent success. 
  - Attached picture, please excuse the wires.
![tarantula bug](https://user-images.githubusercontent.com/3422323/31740919-bbf68bcc-b420-11e7-938b-76eb94e34406.jpg)

**Comment by JimBrown** [comment]
Sorry, can't help you with this, nothing to do with the firmware. Sounds like a mechanical or electronics issue with your display and/or control board. Might want to try asking in official Marlin repository here: https://github.com/MarlinFirmware/Marlin
