### ISSUE TITLE
Mesh Bed Levelling not working when printing

### ISSUE THREAD

**Issue by chanddan** [JimBrown/MarlinTarantula#18]
I have a Tevo Tarantula  and i'm trying to get the Bed Level (Mesh/Manual) feature to work.

I go through the steps in Prepare -> Bed Levelling -> Bed Level, everything seems fine. I also saved the settings.

But when I print, the z-axis does not move. I have tried toggling "Bed Levelling On" and "Bed Levelling Off". Same issue.

Am I doing something wrong or have I discovered a bug?

**Comment by kingcocomango** [comment]
I have UML set, and while the options show up they literally do nothing. There is no response, on/off, attempting to start leveling does nothing, etc.

**Comment by JimBrown** [comment]
@chanddan, you need to add something to your start script to load and activate the mesh you generated and saved. I believe it is M420 S1 to do that. Should be placed immediately after G28 in the start script. You can also add a Z parameter to that, which will slowly fade out the mesh correction up to the given height and then not use it above that height. For example, M420 S1 Z5 will load and activate the mesh compensation, and fade it out over the first 5 mm.

**Comment by JimBrown** [comment]
@kingcocomango, I'm not sure what you mean my "UML"?

**Comment by chanddan** [comment]
Thanks @JimBrown, I'll try M420 S1 and will report back soon.

**Comment by chanddan** [comment]
@JimBrown M420 S1 did the trick, thanks again.
