### ISSUE TITLE
Y Axis Does Not Activate

### ISSUE THREAD

**Issue by roygilby** [JimBrown/MarlinTarantula#2]
Greetings,

I'm not sure if I have a bug to report, or whether I have had "finger trouble" on my part.  Today I flashed your "Tarantula-04" firmware to my Large Bed Tevo Tarantula that does not have auto bed levelling.  The only changes that I have made to your configuration.h file are:

1. Change Hot End Thermistor type setting to suit E3Dv6  (TEMP_SENSOR_0 5).
2. PID Tune on both Hot End and Hot Bed, and entered those values into the relevant places.

I did my initial functional tests using the printers control panel.   X, Y, Z, and E0 all worked and in the correct direction when tested by the control panel manually moving each axis.

However, when I Home All Axes, only the X Axis and the Z Axis move to zero.  The Y Axis never moves - it stays wherever it last landed.

I then tried the same moves using Octoprint to send the commands, and got the same results.  An attempt to print showed that the Y Axis was not moving.  I've since re-flashed my previous working firmware, and the printer is again functioning normally, so that confirms that there are no printer faults causing the problem.

I've double checked my changes and can see no errors that may cause a problem. 

Can you please advise whether I'm looking at a software bug, or whether it's my finger trouble ?

Many thanks,

Roy Gilby

**Comment by JimBrown** [comment]
Hi Roy, sorry for the delayed response, I've been out of the country.

Most likely it is finger trouble, as no one else is reporting the same issue. I did take a quick look through that config file comparing it to the config file I use on my own printer and don't see anything that would cause your issue.

Best suggestion it to download a new copy and try again, carefully comparing the values from your old config file to the new one.

Good luck!
...jim
