### ISSUE TITLE
Babystepping 0.250mm

### ISSUE THREAD

**Issue by st3fan87** [JimBrown/MarlinTarantula#22]
### Bug Report
- Description: The latest version of marlin 1.1.x has a problem with babystepping. Flashed marlin with babystepping enabled and then used m502 and m500. When using babystepping the nozzle goes 0.250mm up or down
- Expected behaviour: nozzle should normally go 0.001mm up/down

**Comment by JimBrown** [comment]
My bad. For some reason I changed the multiplicator from 1 to 100. I've changed it back.

You can download a new copy of the firmware, or you can edit configuration_adv.h and find this line:

**Comment by st3fan87** [comment]
Great, thanks for the quick response
