### ISSUE TITLE
Missing Tevo Tarantula file

### ISSUE THREAD

**Issue by Kpat1** [JimBrown/MarlinTarantula#27]
Marlin/example_configurations/Tevo Tarantula does not exist. I am trying to follow the directions on https://youtu.be/-sQ8p00pG5E and cant get very far without the Tevo Tarantula configuration files.

**Comment by JimBrown** [comment]
My bad. While fixing something else, I inadvertently deleted them. They are back now. Please download a new copy.

Thanks.

**Comment by f-wilhelm** [comment]
Sorry, still or again not online
