### ISSUE TITLE
[FR] Dual Extruder coords on screen

### ISSUE THREAD

**Issue by edgary777** [JimBrown/MarlinTarantula#29]
When Dual Extruder is selected only the Z coord is displayed on the screen because the second nozzle temp displaces them.
Could the rolling message on the lower row be replaced with the XYZ coords?

**Comment by JimBrown** [comment]
Nice idea. However, I do not write the actual code for Marlin, I just provide an easier way to configure it. Highly recommend that you open this same issue on the official Marlin repository at https://github.com/MarlinFirmware/Marlin/issues.
