### ISSUE TITLE
after g29 command not starting to print for tevo tarantula 02.

### ISSUE THREAD

**Issue by wingsaber** [JimBrown/MarlinTarantula#3]
after g29 command not starting to print for tevo tarantula 02. and I couldnt understand why is this happening

**Comment by wingsaber** [comment]
but if ı dont use g29 it starts. im using simplyfy3d

**Comment by JimBrown** [comment]
What does your start script look like? (I also use Simplify3D.)

...jim

**Comment by JimBrown** [comment]
I've just updated my fork with the latest changes from Marlin. Try downloading and trying it again.

...jim

**Comment by wingsaber** [comment]
sorry for late reply. I used m105 command after g29 it started. I will look new update too thanks.

**Comment by JimBrown** [comment]
Sounds like your start gcode is not quite optimized. Might want to ask about that either in the Marlin Firmware issues, or the Facebook Tevo Tarantula group.
