### ISSUE TITLE
EEPROM data Size

### ISSUE THREAD

**Issue by delboy2028** [JimBrown/MarlinTarantula#33]
I am getting the following errors with the latest release downloaded today.

when saving with M500 it saves when entering M501 i get
SENDING:M501
Error:EEPROM datasize error.
[ERROR] Error:EEPROM datasize error.

echo:Index: 582 Size: 653
echo:Hardcoded Default Settings Loaded

when i connect to the printer i get
Printer is now online.
echo:Marlin bugfix-1.1.x
echo: Last Updated: 2017-10-24 12:00 | Author: (Jim Brown, TEVO Tarantula config)
echo:Compiled: Jan  9 2018
echo: Free Memory: 3367  PlannerBufferBytes: 1344
echo:EEPROM version mismatch (EEPROM=V47 Marlin=V49)
echo:Hardcoded Default Settings Loaded
echo:SD init fail

Thank you for submitting your feedback to the Marlin project.
Please use one of the templates below to fill out this box.

------------------------------------------------------------
### Feature Request
Please put [FR] in the issue title: `[FR] Add-on that goes 'ping'`

------------------------------------------------------------
### Compile Error
When I compile with `FEATURE_X` I get an error:
```
Paste_the_error_text_here
```

------------------------------------------------------------
### Bug Report
- Description: ---
- Expected behaviour: ---
- Actual behaviour: ---
- Steps to reproduce:
  - Do this
  - Do that

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

------------------------------------------------------------
### Bug Report Tips
- When troubleshooting, use `M502` followed by `M500` to reset EEPROM to defaults.
- Use `DEBUG_LEVELING_FEATURE` with `M111 S247` for detailed logging of homing/leveling.
- Format text with: **bold**, _italic_, `code`.
- Format C++ with three backticks, plus "cpp":
```cpp
void my_function(bool do_it) {
  // Hold this spot
}
```

**Comment by JimBrown** [comment]
Sorry for the delay responding, for some reason I did not get a notification of your post.

You will get the above whenever the EEPROM code in the firmware has been changed (what gets saved/retrieved to/from EEPROM). This is why it is always advisable to do an M502 first, to make sure the settings configured in firmware are loaded to memory, and then do an M500 to save those settings to EEPROM. Doing the M500 will also update the EEPROM version such that you will no longer have the issue when you send an M501.
