### ISSUE TITLE
Sentence formation is incorrect. 

### ISSUE THREAD

**Issue by satyagupta** [JimBrown/MarlinTarantula#36]
Thanks for taking the pain and doing this for the tevotaratula. Big big thanks for this,

The config has very very small issue. 

the config to change the Y axis motor direction says this _If your bed homes in the wrong direction front to back, enable this._ But as per my understanding from front to back is right direction if its back to front then its wrong or opposite direction.

Its very small thing but sometimes it matters.

**Comment by JimBrown** [comment]
Thanks for that. I've clarified the comments for all three of the change direction parameters.
