### ISSUE TITLE
tevo firmware 

### ISSUE THREAD

**Issue by MaTchoMAN** [JimBrown/MarlinTarantula#43]
trying to follow the vid guide https://youtu.be/-sQ8p00pG5E but the Marlin/example_configurations/Tevo Tarantula doesn't seem to be there, thanks.

**Comment by ThomasM1960** [comment]
"See this video for an excellent tutorial on using this firmware. (NOTE: It is no longer necessary to copy the configuration files from the example configurations folder.)"

**Comment by AElbaum** [comment]
oops, sorry for that. Didnt read that and just watched the video

**Comment by JimBrown** [comment]
Glad you got it figure out. Sorry for the delay responding, didn't get notified of the post.
