### ISSUE TITLE
EasyConfig-1.1.x passing 3 variables to 2 variable function

### ISSUE THREAD

**Issue by SethM55** [JimBrown/MarlinTarantula#44]
Hello,

I jsut downloaded Marlin 1.1.x and after going through easyconfig settings and trying to upload using Arduino 1.8.5 I got an error that lines 2472 and 2477 in Marlin_main.cpp are calling:
`ubl.get_z_correction(pos[X_AXIS], pos[Y_AXIS], pos[Z_AXIS]);`
but `get_z_correction` in ubl.h has no Z_AXIS component.

**Comment by JimBrown** [comment]
Please download a new copy of EasyConfig-1.1.x and try again. There were some updates to the code recently. If the problem persists, please zip your configuration.h and configuration_adv.h files and drop them here. Thanks.

**Comment by SethM55** [comment]
That cleared it up, thanks.
