### ISSUE TITLE
Z lift disables Z stepper driver

### ISSUE THREAD

**Issue by vansoest** [JimBrown/MarlinTarantula#48]
### Description

When I activate the z lift setting from 0 to 0.6 and start the print, the z motor / z driver will be disabled. The movement of the z-axis is then completely disabled, but all other stepper drivers are working. It's not related to the G code on the SD card, the problem also affects normal firmware operations: when I press pause, the printer will also only use X/Y and never move up with Z.

### Steps to Reproduce

1. Enable z lift in Slic3rPE from 0 to 0.6.
2. Start the print from SD card.
#### or:
1. Enable z lift with the Auto retract settings in the firmware from 0 to 0.6.
2. Start the print from SD card.

**Expected behavior:** 
Normally the Z stepper motor should work.

**Actual behavior:**
The z-axis is completely disabled! X,Y,E0 but are working. No gcode for Z works.

#### Additional Information

* Using TMC2130 with external step-up converters (38V) with an MKS Base 1.4.
* Using the nightly build from EasyConfig-1.1.x. 02c4bb0972cfcf6ba2b4318cb411e35250bbe3d7
[Configuration header.tar.gz](https://github.com/JimBrown/MarlinTarantula/files/2231018/Configuration.header.tar.gz)

**Comment by JimBrown** [comment]
I pretty much only play with the configuration files. I don't really know anything about the TMC drivers. And here's the cop out... It all works for me.

Best bet would be to ask this one in the official Marlin repository issues page.

Good luck!
