### ISSUE TITLE
Configured for Tevo Tarantula 

### ISSUE THREAD

**Issue by pedro151** [JimBrown/MarlinTarantula#52]
where I found Configured for Tevo Tarantula release 1.1.0?

**Comment by ThomasM1960** [comment]
did you read this:
"Open configuration.h file in a text editor and make the changes at the top (EasyConfig) section of the file. You should not have to make any other changes."....
and this:
"(NOTE: It is no longer necessary to copy the configuration files from the example configurations folder.)"[https://github.com/JimBrown/MarlinTarantula](url)

**Comment by Marvinarduino** [comment]
My extruder motor isn't moving at all. I checked it and the motor is perfectly fine.
any idea why?
