### ISSUE TITLE
Prints Mid Air

### ISSUE THREAD

**Issue by pirogeth** [JimBrown/MarlinTarantula#58]
Good day to you Jim. This has been super easy to flash with new firmware. That being said i have adjusted the values as required by my probe offset. Also adjusted the bed as required for my Black Widow. The problem i am having is when the BlTouch does the Autohome/ Autolevel it begins printing in mid air. I am not sure what is going on here 

[Configuration.txt](https://github.com/JimBrown/MarlinTarantula/files/2574009/Configuration.txt)

Also my babystepping doesnt go below Z0. after it hits Z0 it disables babystepping.

**Comment by pirogeth** [comment]
Also babystepping is on, but babystep doesnt work either.

**Comment by JimBrown** [comment]
Try this: https://github.com/JimBrown/MarlinTarantula/wiki/Setting-the-Z-height-offset
