### ISSUE TITLE
Print not starts in the middle

### ISSUE THREAD

**Issue by wingsaber** [JimBrown/MarlinTarantula#6]
Hi jim,

I have problem with centered printing and after auto level it is not starting in the middle and it goes front. I tried to print bigger objects and it went outside the bed. I couldnt solve this issue yet I'm trying different variations no good so far.  and in auto level it doesnt go back that much so I wrote 220 to Y and it went back more but still. It doesnt effect anything to print in the middle.

**Comment by JimBrown** [comment]
I'm not at home until late July, but there are some adjustments you need to make to get your prints centered. There is a post on the Tarantula Facebook group from me that has instructions on how to do it. You may have to search for it.

Regards,
…jim
