### ISSUE TITLE
SETTING UP EASY CONFIG - CANNOT JOG PAST Z0 VIA LCD OR REPETIER MANUAL 

### ISSUE THREAD

**Issue by vk2gib** [JimBrown/MarlinTarantula#62]
HI JIM AND ALL

i am new to marlin and easy config.. Im following step by step instructional setups here.

prior to marlin i could jog nozzles to bed and set my SN04 sensor to mark predetermine Zero (0)

NOW with Easy config loaded and setting all zeros i have come to Z.
my printer thinks it has a zero set and i CANNOT jog past zero , via lcd or Repetier manual control.

what am i doing wrong?
is there an ENABLE Z- (minus) movement manually somewhere?

I have googled searched for an answer and also here for the obvious but coming up blank.
Something is blocking me - A SAFE MODE maybe.

any info appreciated. Marty

**Comment by JimBrown** [comment]
Apologies for the delay, I've been otherwise occupied.

Please see this wiki article for setting the Z height:

https://github.com/JimBrown/MarlinTarantula/wiki/Setting-the-Z-height-offset
