### ISSUE TITLE
SD Card, Cannot read

### ISSUE THREAD

**Issue by 3D-og** [JimBrown/MarlinTarantula#65]
Updated to easy config 2.0x and enabled SD card support.

Display says SD card inserted but when I navigate to the SD card, says NO SD CARD.

Worked before update so not hardware issue.

Tried several SD cards including fresh formatted card with no files.

Tried slowing the SD speed to 1/2 and 1/8.

Still no luck.

Seems to recognize the SD card is inserted just fine. As soon as I insert the card, the  main menu says SD CARD INSERTED. However, when I navigate down to the SD card ( one menu down ) says NO SD CARD.

Found two places to enable the SD card;
#define SDSUPPORT (in beginning of the Configuration h and was already enabled)

and again lower in the configuration h;

/**
 * SD CARD
 *
 * SD Card support is disabled by default. If your controller has an SD slot,
 * you must uncomment the following option or it won't work.
 *
 */
//#define SDSUPPORT

/**
 * SD CARD: SPI SPEED

Tried not changing anything, enabling both (uncommenting) the first and second occurrence of #define SDSUPPORT

Both have no affect.

Stock TEVO
Dual Print, Single nozzle.
Large bed.
Gen 1.4 board.

**Comment by JimBrown** [comment]
Tested on my printer (original Tevo with MKS Base 1.4 board) and it is working as it should. Since the purpose of my repository is only to provide an easy way to configure the firmware and that none of the actual code is modified, I can only recommend that you post your issue in the official Marlin repository issues section at https://github.com/MarlinFirmware/Marlin/issues

Good luck and I hope you find and fix the issue.

**Comment by 3D-og** [comment]
Thanks for the reply.

Stubbornly working on the problem and making some progress.

I will post my problem and any solution I find to the /issues

Thanks again for the reply.

**Comment by tomukas1990** [comment]
Any success with this problem? I have same problem with same board (GEN 1.4) and Marlin 2.0 firmware...

**Comment by 3D-og** [comment]
yes.. I traced the problem back to ‘sort file names’ option.

I disabled that feature and works now.
