### ISSUE TITLE
m49 error

### ISSUE THREAD

**Issue by tdude0317** [JimBrown/MarlinTarantula#66]
when i try to verify the code I get this error even when i haven't changed anything

sketch\src\gcode\bedlevel\ubl\M49.cpp:34:22: error: no 'void GcodeSuite::M49()' member function declared in class 'GcodeSuite'

 void GcodeSuite::M49() {

                      ^

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560

how would i fix this?

**Comment by JimBrown** [comment]
It is compiling fine for me. Are you using the latest version of Arduino IDE?

**Comment by tdude0317** [comment]
yes I am but it still comes up with the error
i will try uninstalling and reinstalling the files and possibly arduino though

**Comment by tdude0317** [comment]
ok reinstalling both the code and arduino did it
