### ISSUE TITLE
Please add SERVO_PROBE_OPTIC_ENDSTOP

### ISSUE THREAD

**Issue by peekpt** [JimBrown/MarlinTarantula#69]
I built this Probe which has an optical endstop. 
https://www.thingiverse.com/thing:3756428

Using the SERVO_PROBE config I had to override it with this definitions:
#define Z_MIN_PROBE_ENDSTOP_INVERTING false 
#define Z_MIN_ENDSTOP_INVERTING false 

Could you please add a config with SERVO_PROBE_OPTIC_ENDSTOP

**Comment by JimBrown** [comment]
Since it is unlikely there will be very many people building and using this probe, it's not really worth adding to the EasyConfig section. Anyone doing this should already know how to modify the firmware as you did.

Cool probe though!
