### ISSUE TITLE
upload issue

### ISSUE THREAD

**Issue by dimaknight1109** [JimBrown/MarlinTarantula#70]
Hi there, hoping you or someone can shed some light on the following issue i have experienced.
I recently updated my marlin to show that I'm now running a titan direct drive.
I did the nessessary changes in the file and while reflashing the motherboard with the new version I noticed on the printers display panel showing "cool down" Now my printer is cold as i have not been running it for the past 3 hours.

If i reflash the printer will this fix what ever the problem is or is it something more critical?

**Comment by JimBrown** [comment]
This does not look like an issue with the EasyConfig stuff. Best bet, if this is still a problem, is to ask in the issues section of the official Marlin repository.
