### ISSUE TITLE
Marlin 2.0 easy config m999 reset heater error

### ISSUE THREAD

**Issue by KirkSturg** [JimBrown/MarlinTarantula#71]
So I have done the easy config marlin 2.0.  Prior to this I was running orginal firmware and printing fine.  I did the update in order to install the Bl touch probe.  Since the installation I am not getting this error

 Error:Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)

I am using pronterface to calibrate the bl touch z stop.   It homes and does self test fine then as soon as self test finishes I get that error.  

I have tried everything I read on here and in forums nothing is stopping it from happening.  I never touched the temperature probe only installed the BL touch via front fan mount with two screws.  I then wired it to the board which is a MKS Base v1.4.  I then turned the printer on it self tested fine.  I then installed your firmware update and that's when the issues started happening.

If you can provide any info it would be greatly appreciated!
I have attached a copy of the h and adv
[MarlinTarantula-EasyConfig-2.0.x.zip](https://github.com/JimBrown/MarlinTarantula/files/3740758/MarlinTarantula-EasyConfig-2.0.x.zip)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by JimBrown** [comment]
Best bet at this time is to download a new copy of the firmware, set everything up in the config file again (don't copy the old file over the new file) and try again.
