### ISSUE TITLE
Few questions about this project

### ISSUE THREAD

**Issue by WithoutCaps** [JimBrown/MarlinTarantula#74]
# Description
Hi, 
I was wondering about the state of this project, I see that the last release was made ages ago but it seems to be actively worked on Marlin 2.x. 

1. Is it relatively stable?
2. Is the next release planned anytime soon? Thoughts on Alpha/Beta release?
3. Are testers needed? I could flash my printer and check if everything works as expected.
4. Are there any quality/speed improvements compared to the latest release?

**Comment by JimBrown** [comment]
Your questions would be better posed to the official Marlin repository at https://github.com/MarlinFirmware/Marlin. This repository (fork) is simply for modifications to the configuration files to enable Tevo Tarantula printer owners to easily configure Marlin for their printers. There are no changes to the actual Marlin code itself. Occasionally I update the code in this fork from the official Marlin repository.
