### ISSUE TITLE
Error after Nozzle heating

### ISSUE THREAD

**Issue by Nalofox** [JimBrown/MarlinTarantula#77]
### Description

I have one extruder on E0.
After the nozzle reach is temperature. I got this error

`heating failed E1 

please restart`

### Steps to Reproduce

Slice with filament temperature at 205°C

#### Additional Information

[Configuration.txt](https://github.com/JimBrown/MarlinTarantula/files/5900054/Configuration.txt)
[test.txt](https://github.com/JimBrown/MarlinTarantula/files/5900057/test.txt)

I try to slice at 190°C, error doesn't happend

**Comment by JimBrown** [comment]
Apologies for the delay responding. This does not appear to be an issue with "EasyConfig". If you are still having this issue, please go to the official Marlin repository for assistance.
